k8smg:
  restart: unless-stopped
  image: k8smg:latest
  volumes:
    - /var/log/supervisor/:/var/log/supervisor/
    - /sys/fs/cgroup:/sys/fs/cgroup
  ports:
    - "8001:80"
  hostname: k8s-exec01


  # docker-compose up -d
  # docker-compose down
  # 接口测试: http://k8s.yangmv.com:8001/v1/k8s/publish/